# CI Pipeline — lint, typecheck, test, coverage
# Scaffolded by metaswarm init. Customize for your project.

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Lint, Test & Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Test with coverage
        run: |
          if [ -f .coverage-thresholds.json ]; then
            # Read command from coverage config
            CMD=$(node -e "console.log(JSON.parse(require('fs').readFileSync('.coverage-thresholds.json','utf-8')).enforcement.command)")
            echo "Running coverage command: $CMD"
            # Split into array for safe execution
            read -ra CMD_ARRAY <<< "$CMD"
            # Validate first word is a known package manager/runner
            case "${CMD_ARRAY[0]}" in
              npm|pnpm|yarn|npx|bun|cargo|pytest|go|make) ;;
              *) echo "Error: enforcement command must start with a known package manager/runner"; exit 1 ;;
            esac
            # Reject shell metacharacters in the full command string
            if echo "$CMD" | grep -qE '[;|&`$(){}<>\\]'; then
              echo "Error: enforcement command contains disallowed shell metacharacters"
              exit 1
            fi
            # Execute as array — prevents all shell metacharacter interpretation
            "${CMD_ARRAY[@]}"
          else
            npm test
          fi
